lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.17466836489936924
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.009757257741652123
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 3.000954864696886
    motion_trans_pos_noise_scale: 1.5023450878551516
    visualize: false
    map_voxel: 0.1382376554755013
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.00015352264861357914
    ieskf_sigma_accel: 0.06618713906929864
    ieskf_sigma_bg: 0.00021313707319551022
    ieskf_sigma_ba: 0.0003160193476925529
    ieskf_init_p_cov: 0.012529923989151797
    ieskf_init_bg_cov: 0.03294379094484595
    ieskf_init_ba_cov: 0.01083897944735442
    ieskf_init_g_cov: 0.04044981514921887
    ieskf_max_iters: 6
    ieskf_meas_noise_pos: 0.0016139554564837246
    ieskf_meas_noise_rot: 0.016913245790196797
    imu_base_weight: 0.5917573421138594
    nonrep_base_weight: 0.40824265788614056
    gicp_min_conf: 0.4961783325684115
    gicp_chi2_threshold: 23.00093973068246
    use_pctools_gicp: true
    gicp_max_corr_distance: 3.307250656821329
    gicp_voxel_size: 0.29771783676411906
    gicp_max_iterations: 78
    gicp_submap_radius: 12.549532276004609
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
