lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.14963195523140427
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.0047332667509673056
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 3.4527340421368082
    motion_trans_pos_noise_scale: 1.3810779900433439
    visualize: false
    map_voxel: 0.07860865635052845
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.006331639152617073
    ieskf_sigma_accel: 0.02389513347575667
    ieskf_sigma_bg: 0.00018375123416440297
    ieskf_sigma_ba: 0.00012569190684958182
    ieskf_init_p_cov: 0.021332173731163334
    ieskf_init_bg_cov: 0.00478244247251219
    ieskf_init_ba_cov: 0.008551650429171765
    ieskf_init_g_cov: 0.0003042949880496156
    ieskf_max_iters: 5
    ieskf_meas_noise_pos: 0.0023682537261756798
    ieskf_meas_noise_rot: 0.006967880740043633
    imu_base_weight: 0.54453682517723
    nonrep_base_weight: 0.45546317482277
    gicp_min_conf: 0.37478254740531614
    gicp_chi2_threshold: 20.805837704947518
    use_pctools_gicp: true
    gicp_max_corr_distance: 2.3883154711297143
    gicp_voxel_size: 0.13742404966915364
    gicp_max_iterations: 46
    gicp_submap_radius: 14.569342534611785
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
