lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.17540663211673954
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.003281701419740088
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 1.2780884469866487
    motion_trans_pos_noise_scale: 1.6011098456414234
    visualize: false
    map_voxel: 0.2543506602546319
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.002918295874868646
    ieskf_sigma_accel: 0.025309404112781972
    ieskf_sigma_bg: 2.1167026598851006e-05
    ieskf_sigma_ba: 0.001787374809940258
    ieskf_init_p_cov: 0.0031148523281465043
    ieskf_init_bg_cov: 0.06498930183878102
    ieskf_init_ba_cov: 0.022579016042252823
    ieskf_init_g_cov: 0.00041843252779838203
    ieskf_max_iters: 6
    ieskf_meas_noise_pos: 0.03524785187917275
    ieskf_meas_noise_rot: 0.009969297445768664
    imu_base_weight: 0.5748635912035269
    nonrep_base_weight: 0.4251364087964731
    gicp_min_conf: 0.26785502941661227
    gicp_chi2_threshold: 136.49618442870252
    use_pctools_gicp: true
    gicp_max_corr_distance: 2.648718703223381
    gicp_voxel_size: 0.3306630570690581
    gicp_max_iterations: 32
    gicp_submap_radius: 7.554969303507377
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
