lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.12783604845716331
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.0019842920620406577
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 2.453353987160824
    motion_trans_pos_noise_scale: 1.9943379388791291
    visualize: false
    map_voxel: 0.2953523171821924
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.001012790863154233
    ieskf_sigma_accel: 0.024209859204561784
    ieskf_sigma_bg: 0.0001179513979448032
    ieskf_sigma_ba: 0.007370043201946365
    ieskf_init_p_cov: 0.012843506765589877
    ieskf_init_bg_cov: 0.003609556190452908
    ieskf_init_ba_cov: 0.005721970377133915
    ieskf_init_g_cov: 0.021956496645434895
    ieskf_max_iters: 5
    ieskf_meas_noise_pos: 0.014581886822668911
    ieskf_meas_noise_rot: 0.005846713848875905
    imu_base_weight: 0.7154864976505327
    nonrep_base_weight: 0.28451350234946726
    gicp_min_conf: 0.24143083297411874
    gicp_chi2_threshold: 94.08461218036393
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.170382200762893
    gicp_voxel_size: 0.3133065171296242
    gicp_max_iterations: 20
    gicp_submap_radius: 9.09407075458213
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
