lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.3919946797782136
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.006731259028411225
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 3.2706035614317734
    motion_trans_pos_noise_scale: 1.098328417391785
    visualize: false
    map_voxel: 0.08622628081759857
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.0008670692864628845
    ieskf_sigma_accel: 0.079631969776111
    ieskf_sigma_bg: 3.5474678253355484e-05
    ieskf_sigma_ba: 0.0009178359151483669
    ieskf_init_p_cov: 0.006415873857139275
    ieskf_init_bg_cov: 0.02194623061311748
    ieskf_init_ba_cov: 0.0044360070613190476
    ieskf_init_g_cov: 0.007241888984268679
    ieskf_max_iters: 5
    ieskf_meas_noise_pos: 0.009064050926681036
    ieskf_meas_noise_rot: 0.004901584313265161
    imu_base_weight: 0.36878150208898336
    nonrep_base_weight: 0.6312184979110167
    gicp_min_conf: 0.3503049641210321
    gicp_chi2_threshold: 144.68499422992542
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.2809091155736052
    gicp_voxel_size: 0.15422696625588345
    gicp_max_iterations: 88
    gicp_submap_radius: 11.57549220112225
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
