lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.11695010998160078
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.028439994205734457
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 7.0191917060900995
    motion_trans_pos_noise_scale: 3.7392910668303845
    visualize: false
    map_voxel: 0.0988119951185946
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.0019362537744433681
    ieskf_sigma_accel: 0.02770047394469448
    ieskf_sigma_bg: 0.00024216653449940533
    ieskf_sigma_ba: 0.00043954153303034024
    ieskf_init_p_cov: 0.015477464507371978
    ieskf_init_bg_cov: 0.00029981978999879083
    ieskf_init_ba_cov: 0.02047147040324719
    ieskf_init_g_cov: 0.0017327814268057046
    ieskf_max_iters: 5
    ieskf_meas_noise_pos: 0.43998745468788714
    ieskf_meas_noise_rot: 0.0010161056084037532
    imu_base_weight: 0.6414147251698596
    nonrep_base_weight: 0.35858527483014035
    gicp_min_conf: 0.05648649132674513
    gicp_chi2_threshold: 92.73904356303996
    use_pctools_gicp: true
    gicp_max_corr_distance: 0.5276362494581062
    gicp_voxel_size: 0.05054756270086759
    gicp_max_iterations: 38
    gicp_submap_radius: 39.096293116251196
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
