lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.2985790980609124
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.0066635239320191305
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 2.0406783259571197
    motion_trans_pos_noise_scale: 0.675959365977642
    visualize: false
    map_voxel: 0.09875414487707043
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.00972404772569559
    ieskf_sigma_accel: 0.03347799101822025
    ieskf_sigma_bg: 1.3910060479849248e-05
    ieskf_sigma_ba: 0.0002545383535507043
    ieskf_init_p_cov: 0.003369683474690309
    ieskf_init_bg_cov: 0.041237957780049475
    ieskf_init_ba_cov: 1.3566840982681416e-05
    ieskf_init_g_cov: 0.0001011579791610711
    ieskf_max_iters: 6
    ieskf_meas_noise_pos: 0.13123616162028529
    ieskf_meas_noise_rot: 0.008828042081640553
    imu_base_weight: 0.2692955247140225
    nonrep_base_weight: 0.7307044752859775
    gicp_min_conf: 0.4203139725916581
    gicp_chi2_threshold: 168.73699293717232
    use_pctools_gicp: true
    gicp_max_corr_distance: 2.214763325362382
    gicp_voxel_size: 0.08251679199748858
    gicp_max_iterations: 22
    gicp_submap_radius: 13.355264395741454
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
