lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.20607857698797685
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.09207153076274126
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 5.067147034241865
    motion_trans_pos_noise_scale: 1.414124674678634
    visualize: false
    map_voxel: 0.10158384110009118
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.002442283347006287
    ieskf_sigma_accel: 0.0059692870818741
    ieskf_sigma_bg: 0.00010819037501282728
    ieskf_sigma_ba: 0.003868327914860676
    ieskf_init_p_cov: 9.12664747970252
    ieskf_init_bg_cov: 0.014076355781672831
    ieskf_init_ba_cov: 0.007359202611320763
    ieskf_init_g_cov: 0.0005309477520631866
    ieskf_max_iters: 4
    ieskf_meas_noise_pos: 0.009141168705134296
    ieskf_meas_noise_rot: 0.002037000158385144
    imu_base_weight: 0.49563568617270026
    nonrep_base_weight: 0.5043643138272997
    gicp_min_conf: 0.13445857440829173
    gicp_chi2_threshold: 105.32469995844075
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.3160838891368982
    gicp_voxel_size: 0.0697854667247205
    gicp_max_iterations: 30
    gicp_submap_radius: 35.10144142787098
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
