lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.24906447158811412
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.011751230908174965
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 1.446767131291615
    motion_trans_pos_noise_scale: 0.7292363512898032
    visualize: false
    map_voxel: 0.10420134114330594
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.0074864995667376436
    ieskf_sigma_accel: 0.015052826823567365
    ieskf_sigma_bg: 2.129998955487012e-05
    ieskf_sigma_ba: 0.0001703171002031299
    ieskf_init_p_cov: 0.003370274928022685
    ieskf_init_bg_cov: 0.050282151579022515
    ieskf_init_ba_cov: 0.04662611640918602
    ieskf_init_g_cov: 0.0001162764356470856
    ieskf_max_iters: 6
    ieskf_meas_noise_pos: 0.0559558317486372
    ieskf_meas_noise_rot: 0.014860752682125677
    imu_base_weight: 0.4290175093341343
    nonrep_base_weight: 0.5709824906658657
    gicp_min_conf: 0.47409292603180564
    gicp_chi2_threshold: 192.62732483154045
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.8161362283154285
    gicp_voxel_size: 0.09249419392212364
    gicp_max_iterations: 26
    gicp_submap_radius: 16.508314307934537
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
