lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.2108359398979975
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.0028327982463169765
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 3.010157422187591
    motion_trans_pos_noise_scale: 1.1587467412968433
    visualize: false
    map_voxel: 0.2688149058877062
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.0015253224278213122
    ieskf_sigma_accel: 0.016911070167759702
    ieskf_sigma_bg: 4.4658728761371946e-05
    ieskf_sigma_ba: 0.005661775885294001
    ieskf_init_p_cov: 0.0024171953596007364
    ieskf_init_bg_cov: 0.0001838959654619444
    ieskf_init_ba_cov: 0.0013319668585891388
    ieskf_init_g_cov: 0.0037119369824955874
    ieskf_max_iters: 2
    ieskf_meas_noise_pos: 0.012255020026822161
    ieskf_meas_noise_rot: 0.007576551378488666
    imu_base_weight: 0.8067504334858214
    nonrep_base_weight: 0.19324956651417857
    gicp_min_conf: 0.3315771545063795
    gicp_chi2_threshold: 72.35095122658875
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.5065548531652448
    gicp_voxel_size: 0.391028041413216
    gicp_max_iterations: 36
    gicp_submap_radius: 20.625948133689686
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
