lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.2314503243699987
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.05168998951247787
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 1.110303260141654
    motion_trans_pos_noise_scale: 3.8417122510123853
    visualize: false
    map_voxel: 0.11592349712520797
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.0007704627189540474
    ieskf_sigma_accel: 0.017871085711330326
    ieskf_sigma_bg: 7.123498417990455e-05
    ieskf_sigma_ba: 0.000701551235370352
    ieskf_init_p_cov: 0.26099620827768655
    ieskf_init_bg_cov: 0.013810977128634098
    ieskf_init_ba_cov: 0.018141726528349104
    ieskf_init_g_cov: 0.06101693294713205
    ieskf_max_iters: 6
    ieskf_meas_noise_pos: 0.01672333169746683
    ieskf_meas_noise_rot: 0.0018883087069655816
    imu_base_weight: 0.7825943350200484
    nonrep_base_weight: 0.21740566497995162
    gicp_min_conf: 0.2113386207998849
    gicp_chi2_threshold: 124.81468803897867
    use_pctools_gicp: true
    gicp_max_corr_distance: 2.8876860605871144
    gicp_voxel_size: 0.0640456733110411
    gicp_max_iterations: 33
    gicp_submap_radius: 37.888039886711326
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
