lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.07301217973684306
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.0010179178313543188
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 1.7030151330620185
    motion_trans_pos_noise_scale: 2.363576797817682
    visualize: false
    map_voxel: 0.19526563196808197
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.0007810995663218347
    ieskf_sigma_accel: 0.0685823564811819
    ieskf_sigma_bg: 0.0005255574866739624
    ieskf_sigma_ba: 0.0008032384234296547
    ieskf_init_p_cov: 0.0024336997421522074
    ieskf_init_bg_cov: 0.08786549727362261
    ieskf_init_ba_cov: 0.0007668148342782742
    ieskf_init_g_cov: 0.16188503999222353
    ieskf_max_iters: 6
    ieskf_meas_noise_pos: 0.030134127526992426
    ieskf_meas_noise_rot: 0.03231379587424737
    imu_base_weight: 0.9486769170515832
    nonrep_base_weight: 0.05132308294841681
    gicp_min_conf: 0.38073730276033835
    gicp_chi2_threshold: 32.44134518506554
    use_pctools_gicp: true
    gicp_max_corr_distance: 3.4953364446644946
    gicp_voxel_size: 0.21153576848755928
    gicp_max_iterations: 85
    gicp_submap_radius: 8.403287562160392
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
