lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.19309528511710086
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.003708931837358665
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 2.5477109315572015
    motion_trans_pos_noise_scale: 0.46588997159156686
    visualize: false
    map_voxel: 0.13372176116253118
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.004214459132673093
    ieskf_sigma_accel: 0.004248292387623102
    ieskf_sigma_bg: 5.456748261758373e-05
    ieskf_sigma_ba: 0.0015150368991769603
    ieskf_init_p_cov: 0.0010019847754600564
    ieskf_init_bg_cov: 4.025885102093691e-05
    ieskf_init_ba_cov: 0.012727238426475489
    ieskf_init_g_cov: 0.0028718229273892518
    ieskf_max_iters: 6
    ieskf_meas_noise_pos: 0.0018963523882424638
    ieskf_meas_noise_rot: 0.0025405332689007647
    imu_base_weight: 0.7035032562571252
    nonrep_base_weight: 0.2964967437428748
    gicp_min_conf: 0.3984607235439268
    gicp_chi2_threshold: 39.71972154550583
    use_pctools_gicp: true
    gicp_max_corr_distance: 3.12553924268554
    gicp_voxel_size: 0.20799708442987458
    gicp_max_iterations: 64
    gicp_submap_radius: 18.831695429715307
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
