lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.11313953580148953
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.013159269648126857
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 8.454086109884225
    motion_trans_pos_noise_scale: 1.836827594507086
    visualize: false
    map_voxel: 0.06615658214438162
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.0024807514186242236
    ieskf_sigma_accel: 0.048968444807536704
    ieskf_sigma_bg: 0.00024216653449940533
    ieskf_sigma_ba: 0.00043954153303034024
    ieskf_init_p_cov: 0.004990768787094603
    ieskf_init_bg_cov: 0.013941300929495823
    ieskf_init_ba_cov: 0.0011392357225195008
    ieskf_init_g_cov: 0.000993775600704924
    ieskf_max_iters: 5
    ieskf_meas_noise_pos: 0.004295260797955278
    ieskf_meas_noise_rot: 0.006426201225550218
    imu_base_weight: 0.22389721299067278
    nonrep_base_weight: 0.7761027870093272
    gicp_min_conf: 0.3426980022709897
    gicp_chi2_threshold: 128.9396057170289
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.3839195326243692
    gicp_voxel_size: 0.13651368040223297
    gicp_max_iterations: 78
    gicp_submap_radius: 43.052661453820704
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
