lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.01630801748725383
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.0034045224465912628
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 1.2086680177291156
    motion_trans_pos_noise_scale: 1.3123745002343754
    visualize: false
    map_voxel: 0.2189333042868048
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.0016670080794270155
    ieskf_sigma_accel: 0.04554272584601241
    ieskf_sigma_bg: 2.743021299926816e-05
    ieskf_sigma_ba: 0.0008741985807203015
    ieskf_init_p_cov: 1.4358137112440263
    ieskf_init_bg_cov: 0.01822002276211775
    ieskf_init_ba_cov: 0.0026142048651632754
    ieskf_init_g_cov: 0.006005758958717411
    ieskf_max_iters: 5
    ieskf_meas_noise_pos: 0.005613607922181755
    ieskf_meas_noise_rot: 0.010089372565870263
    imu_base_weight: 0.557924629179446
    nonrep_base_weight: 0.44207537082055404
    gicp_min_conf: 0.39176028412052344
    gicp_chi2_threshold: 78.514620625898
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.4802773185765243
    gicp_voxel_size: 0.28568019990192645
    gicp_max_iterations: 77
    gicp_submap_radius: 38.9489871050979
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
