lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.09586437086035712
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.0013599242436074417
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 3.5648130182798066
    motion_trans_pos_noise_scale: 2.6893568699597874
    visualize: false
    map_voxel: 0.21758748055558402
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.0017358485015412427
    ieskf_sigma_accel: 0.012851566830726358
    ieskf_sigma_bg: 7.028552274561472e-05
    ieskf_sigma_ba: 0.009570295918819107
    ieskf_init_p_cov: 0.04378884416727118
    ieskf_init_bg_cov: 1.6791434049246414e-05
    ieskf_init_ba_cov: 0.013351003848471156
    ieskf_init_g_cov: 0.0025546251710322813
    ieskf_max_iters: 6
    ieskf_meas_noise_pos: 0.021866520795145467
    ieskf_meas_noise_rot: 0.002325558488513979
    imu_base_weight: 0.6934253083471598
    nonrep_base_weight: 0.30657469165284024
    gicp_min_conf: 0.28051051513761344
    gicp_chi2_threshold: 118.08376241941423
    use_pctools_gicp: true
    gicp_max_corr_distance: 0.7933839902000451
    gicp_voxel_size: 0.3650594416306595
    gicp_max_iterations: 80
    gicp_submap_radius: 10.26001444205565
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
