lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.019460007309045277
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.004295706184656975
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 7.28943177019983
    motion_trans_pos_noise_scale: 2.357026584135477
    visualize: false
    map_voxel: 0.1623281532936116
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.0009341729343248032
    ieskf_sigma_accel: 0.08133488404542777
    ieskf_sigma_bg: 5.836099695805216e-05
    ieskf_sigma_ba: 0.0007665765936068734
    ieskf_init_p_cov: 0.00641784865419804
    ieskf_init_bg_cov: 0.001708760835919021
    ieskf_init_ba_cov: 0.0009278621177993139
    ieskf_init_g_cov: 0.004643219151101321
    ieskf_max_iters: 4
    ieskf_meas_noise_pos: 0.0011150176999970341
    ieskf_meas_noise_rot: 0.023017787363971868
    imu_base_weight: 0.6254093010808005
    nonrep_base_weight: 0.3745906989191995
    gicp_min_conf: 0.3644038773265736
    gicp_chi2_threshold: 69.76545749730481
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.1547531977732222
    gicp_voxel_size: 0.2008090310122057
    gicp_max_iterations: 83
    gicp_submap_radius: 12.627712646805755
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
