lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.09680377147920827
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.0019793498995788776
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 2.7426823073205266
    motion_trans_pos_noise_scale: 2.0224472671541958
    visualize: false
    map_voxel: 0.09210572868005565
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.005400704927893926
    ieskf_sigma_accel: 0.008995419187585705
    ieskf_sigma_bg: 0.0002751088457343421
    ieskf_sigma_ba: 0.00016635886352681797
    ieskf_init_p_cov: 0.00903594107515887
    ieskf_init_bg_cov: 0.020835379444924678
    ieskf_init_ba_cov: 0.04985718355413099
    ieskf_init_g_cov: 0.6981665419671174
    ieskf_max_iters: 6
    ieskf_meas_noise_pos: 0.003655833271633954
    ieskf_meas_noise_rot: 0.00376071730459909
    imu_base_weight: 0.42838081198399436
    nonrep_base_weight: 0.5716191880160056
    gicp_min_conf: 0.31837874439432384
    gicp_chi2_threshold: 47.640521626950424
    use_pctools_gicp: true
    gicp_max_corr_distance: 2.098107037963093
    gicp_voxel_size: 0.16650925112500112
    gicp_max_iterations: 26
    gicp_submap_radius: 19.344084667245312
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
