lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.21420444686684575
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.001882181465753874
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 2.3258503918011555
    motion_trans_pos_noise_scale: 1.1950216651519947
    visualize: false
    map_voxel: 0.2730484546080553
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.0017833074672668656
    ieskf_sigma_accel: 0.025725864580252663
    ieskf_sigma_bg: 2.025773362111223e-05
    ieskf_sigma_ba: 0.005362598213116071
    ieskf_init_p_cov: 0.002527834751755912
    ieskf_init_bg_cov: 0.0036497179821639828
    ieskf_init_ba_cov: 0.013841215228763108
    ieskf_init_g_cov: 0.0021011308675577137
    ieskf_max_iters: 6
    ieskf_meas_noise_pos: 0.019010363398542476
    ieskf_meas_noise_rot: 0.007572182094509039
    imu_base_weight: 0.6670003615918159
    nonrep_base_weight: 0.33299963840818414
    gicp_min_conf: 0.26447551761380056
    gicp_chi2_threshold: 94.3443067324934
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.6896879540904384
    gicp_voxel_size: 0.3473693003516435
    gicp_max_iterations: 21
    gicp_submap_radius: 10.070683447838576
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
