lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.15984557577492461
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.005005850799559948
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 3.469978855050486
    motion_trans_pos_noise_scale: 1.3476481749657454
    visualize: false
    map_voxel: 0.07796710425624569
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.007252279369682001
    ieskf_sigma_accel: 0.02057883166378376
    ieskf_sigma_bg: 0.00017068912087083728
    ieskf_sigma_ba: 0.00016552398960187578
    ieskf_init_p_cov: 0.028898008531921066
    ieskf_init_bg_cov: 0.004819869028488025
    ieskf_init_ba_cov: 0.007999009213851547
    ieskf_init_g_cov: 0.0004310211591321471
    ieskf_max_iters: 5
    ieskf_meas_noise_pos: 0.00248654499305917
    ieskf_meas_noise_rot: 0.006501110876834529
    imu_base_weight: 0.4371300895981498
    nonrep_base_weight: 0.5628699104018502
    gicp_min_conf: 0.3739874485811168
    gicp_chi2_threshold: 27.80654454982848
    use_pctools_gicp: true
    gicp_max_corr_distance: 2.3850554931646135
    gicp_voxel_size: 0.1411721159102296
    gicp_max_iterations: 46
    gicp_submap_radius: 14.327778181742186
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
