lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.2241967641036713
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.0012696892155118426
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 1.3285812655799778
    motion_trans_pos_noise_scale: 1.9510294956495353
    visualize: false
    map_voxel: 0.2460640667809888
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.0019534342227972845
    ieskf_sigma_accel: 0.019150896926181014
    ieskf_sigma_bg: 1.2493028452884778e-05
    ieskf_sigma_ba: 0.002154546506924448
    ieskf_init_p_cov: 0.0018197300420328653
    ieskf_init_bg_cov: 0.009730886984805757
    ieskf_init_ba_cov: 0.010874156561506696
    ieskf_init_g_cov: 0.0003635185447026262
    ieskf_max_iters: 6
    ieskf_meas_noise_pos: 0.025228167946615723
    ieskf_meas_noise_rot: 0.0014854679876907906
    imu_base_weight: 0.6486993956226268
    nonrep_base_weight: 0.3513006043773732
    gicp_min_conf: 0.19558857186616882
    gicp_chi2_threshold: 98.3317762960717
    use_pctools_gicp: true
    gicp_max_corr_distance: 3.1347546286311356
    gicp_voxel_size: 0.26920375508458916
    gicp_max_iterations: 28
    gicp_submap_radius: 11.390584016828475
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
