lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.042144229620572855
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.0015393931002140857
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 6.91851603070309
    motion_trans_pos_noise_scale: 2.884712156343811
    visualize: false
    map_voxel: 0.15491423093430018
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.00010235832435175117
    ieskf_sigma_accel: 0.002097085333143113
    ieskf_sigma_bg: 0.00012516058337570362
    ieskf_sigma_ba: 0.0024198608614538677
    ieskf_init_p_cov: 0.7058572590901792
    ieskf_init_bg_cov: 8.891936446296254e-05
    ieskf_init_ba_cov: 0.0002002621122934531
    ieskf_init_g_cov: 0.09682012086882462
    ieskf_max_iters: 6
    ieskf_meas_noise_pos: 0.057494179877722436
    ieskf_meas_noise_rot: 0.0032813337705313913
    imu_base_weight: 0.6471515921972502
    nonrep_base_weight: 0.35284840780274984
    gicp_min_conf: 0.451420949829701
    gicp_chi2_threshold: 133.4302508189708
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.6934106545677645
    gicp_voxel_size: 0.0876919338775243
    gicp_max_iterations: 98
    gicp_submap_radius: 22.689397610004217
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
