lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.2558586885593425
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.003488976654890368
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 3.927972976869379
    motion_trans_pos_noise_scale: 2.004518719478462
    visualize: false
    map_voxel: 0.05714545315186696
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.001096821720752952
    ieskf_sigma_accel: 0.0123999678368461
    ieskf_sigma_bg: 2.3426581058204037e-05
    ieskf_sigma_ba: 0.00869299151113955
    ieskf_init_p_cov: 3.7958531426706403
    ieskf_init_bg_cov: 0.002463768595899745
    ieskf_init_ba_cov: 0.04869640941520897
    ieskf_init_g_cov: 0.00022592797420156976
    ieskf_max_iters: 1
    ieskf_meas_noise_pos: 0.12361188797337339
    ieskf_meas_noise_rot: 0.1451494001648588
    imu_base_weight: 0.33053996848046985
    nonrep_base_weight: 0.6694600315195302
    gicp_min_conf: 0.41098864133931784
    gicp_chi2_threshold: 47.236743859637585
    use_pctools_gicp: true
    gicp_max_corr_distance: 2.105389970121152
    gicp_voxel_size: 0.09547826400522687
    gicp_max_iterations: 63
    gicp_submap_radius: 11.341590123864318
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
