lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.010529650702479954
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.04131731287812945
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 5.543638398607174
    motion_trans_pos_noise_scale: 3.8306602296519867
    visualize: false
    map_voxel: 0.12148667588729599
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.0004957547237088648
    ieskf_sigma_accel: 0.011906605141784356
    ieskf_sigma_bg: 0.00034983170563822173
    ieskf_sigma_ba: 0.0019480005358814756
    ieskf_init_p_cov: 0.0863688414091306
    ieskf_init_bg_cov: 0.0003199756064732436
    ieskf_init_ba_cov: 0.018160795832556947
    ieskf_init_g_cov: 0.010646920348371022
    ieskf_max_iters: 4
    ieskf_meas_noise_pos: 0.408396536195659
    ieskf_meas_noise_rot: 0.0026143783521608713
    imu_base_weight: 0.49643718095274286
    nonrep_base_weight: 0.5035628190472572
    gicp_min_conf: 0.1943825803789177
    gicp_chi2_threshold: 64.32435186820817
    use_pctools_gicp: true
    gicp_max_corr_distance: 2.360363448617208
    gicp_voxel_size: 0.07830757472989393
    gicp_max_iterations: 59
    gicp_submap_radius: 29.818240288998734
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
