lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.0526902008852832
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.0015373109576504486
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 3.9303335215128676
    motion_trans_pos_noise_scale: 1.7172790896080778
    visualize: false
    map_voxel: 0.15419457829928143
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.00312546504364813
    ieskf_sigma_accel: 0.008184842665352327
    ieskf_sigma_bg: 9.292054081215568e-05
    ieskf_sigma_ba: 0.0009513454624021622
    ieskf_init_p_cov: 0.001906571574851538
    ieskf_init_bg_cov: 0.0010264757450100534
    ieskf_init_ba_cov: 0.0017291239448864906
    ieskf_init_g_cov: 0.00018300104360355704
    ieskf_max_iters: 1
    ieskf_meas_noise_pos: 0.0063464026753455435
    ieskf_meas_noise_rot: 0.0013392584390804186
    imu_base_weight: 0.880455205419457
    nonrep_base_weight: 0.11954479458054301
    gicp_min_conf: 0.25596620422474914
    gicp_chi2_threshold: 53.69956192478258
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.8756247960623629
    gicp_voxel_size: 0.12126857059568208
    gicp_max_iterations: 35
    gicp_submap_radius: 24.642962221912516
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
