lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.055950746357947966
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.0233596350262616
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 3.741523922560336
    motion_trans_pos_noise_scale: 0.578593358631281
    visualize: false
    map_voxel: 0.1638749409902834
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.000816845589476017
    ieskf_sigma_accel: 0.037183641805732096
    ieskf_sigma_bg: 2.5081156860452307e-05
    ieskf_sigma_ba: 0.0010677482709481358
    ieskf_init_p_cov: 0.26926469100861794
    ieskf_init_bg_cov: 4.809461967501571e-05
    ieskf_init_ba_cov: 1.8205657658407255e-05
    ieskf_init_g_cov: 0.6245139574743068
    ieskf_max_iters: 5
    ieskf_meas_noise_pos: 0.039710847107924725
    ieskf_meas_noise_rot: 0.0012790390175145834
    imu_base_weight: 0.3797256589643225
    nonrep_base_weight: 0.6202743410356775
    gicp_min_conf: 0.1664509917200076
    gicp_chi2_threshold: 193.47008628416629
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.0491720568015048
    gicp_voxel_size: 0.15636765183901852
    gicp_max_iterations: 22
    gicp_submap_radius: 45.91941809354519
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
