lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.010675232516979126
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.07432308912830163
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 9.82476749585545
    motion_trans_pos_noise_scale: 4.929167021118573
    visualize: false
    map_voxel: 0.2950717318366187
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.00020197761759846444
    ieskf_sigma_accel: 0.0010353677627159778
    ieskf_sigma_bg: 0.0007321173243252613
    ieskf_sigma_ba: 0.00011674940838837022
    ieskf_init_p_cov: 0.04159566743044208
    ieskf_init_bg_cov: 0.06135465318705152
    ieskf_init_ba_cov: 0.09320745757067897
    ieskf_init_g_cov: 0.02300905373674917
    ieskf_max_iters: 3
    ieskf_meas_noise_pos: 0.0012720909211968647
    ieskf_meas_noise_rot: 0.01816685270836173
    imu_base_weight: 0.09382297970021769
    nonrep_base_weight: 0.9061770202997823
    gicp_min_conf: 0.2875005018635144
    gicp_chi2_threshold: 13.840757715131545
    use_pctools_gicp: true
    gicp_max_corr_distance: 4.979950193444586
    gicp_voxel_size: 0.3848334366645898
    gicp_max_iterations: 20
    gicp_submap_radius: 48.05856631494798
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
