lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.12325158377757167
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.036287002255540685
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 9.073992339573193
    motion_trans_pos_noise_scale: 4.446723478899075
    visualize: false
    map_voxel: 0.05996947022946623
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.002089142634385646
    ieskf_sigma_accel: 0.043096738082034555
    ieskf_sigma_bg: 0.00012894414393074176
    ieskf_sigma_ba: 0.0011463075602214
    ieskf_init_p_cov: 3.8802797007866876
    ieskf_init_bg_cov: 0.039964301676942524
    ieskf_init_ba_cov: 0.00340726434853019
    ieskf_init_g_cov: 0.002270487755790924
    ieskf_max_iters: 5
    ieskf_meas_noise_pos: 0.004495231668058586
    ieskf_meas_noise_rot: 0.0016376921277031107
    imu_base_weight: 0.28214746494364
    nonrep_base_weight: 0.71785253505636
    gicp_min_conf: 0.05413867322748334
    gicp_chi2_threshold: 76.34981917640557
    use_pctools_gicp: true
    gicp_max_corr_distance: 0.8786298424777197
    gicp_voxel_size: 0.07254353563117091
    gicp_max_iterations: 92
    gicp_submap_radius: 32.289307684681546
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
