lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.4552174126018115
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.01770473613080686
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 1.5696094275163746
    motion_trans_pos_noise_scale: 0.8491547261275447
    visualize: false
    map_voxel: 0.15259501876927326
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.005171477966866785
    ieskf_sigma_accel: 0.061181993940978285
    ieskf_sigma_bg: 0.00028411822641941195
    ieskf_sigma_ba: 0.0012700212917299489
    ieskf_init_p_cov: 0.0013918621180805967
    ieskf_init_bg_cov: 0.00010260633449680586
    ieskf_init_ba_cov: 0.003145803934990252
    ieskf_init_g_cov: 0.00017340391809724656
    ieskf_max_iters: 5
    ieskf_meas_noise_pos: 0.0332505543557762
    ieskf_meas_noise_rot: 0.004027024624225385
    imu_base_weight: 0.32413839375742437
    nonrep_base_weight: 0.6758616062425756
    gicp_min_conf: 0.45101749732643953
    gicp_chi2_threshold: 186.50219993512684
    use_pctools_gicp: true
    gicp_max_corr_distance: 0.8348149313426116
    gicp_voxel_size: 0.12381821845876355
    gicp_max_iterations: 41
    gicp_submap_radius: 45.31302580651975
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
