lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.082120801543677
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.0025934076314720915
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 1.6266851022640467
    motion_trans_pos_noise_scale: 1.0578079450188653
    visualize: false
    map_voxel: 0.07244959161948308
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.0010458544352547152
    ieskf_sigma_accel: 0.015948916896832203
    ieskf_sigma_bg: 0.00013923050583830517
    ieskf_sigma_ba: 0.008061242249043398
    ieskf_init_p_cov: 0.0058216905585377265
    ieskf_init_bg_cov: 0.09940596955384004
    ieskf_init_ba_cov: 0.004969571370362415
    ieskf_init_g_cov: 0.0011352283898293206
    ieskf_max_iters: 6
    ieskf_meas_noise_pos: 0.0014657658271480696
    ieskf_meas_noise_rot: 0.0048823010527511345
    imu_base_weight: 0.33939902651786796
    nonrep_base_weight: 0.6606009734821321
    gicp_min_conf: 0.4259352303587992
    gicp_chi2_threshold: 10.226138885623755
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.3903043224012892
    gicp_voxel_size: 0.18513150658812585
    gicp_max_iterations: 28
    gicp_submap_radius: 27.311026543560978
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
