lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.018644510057737033
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.013355546608275348
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 5.542428484856815
    motion_trans_pos_noise_scale: 3.2252876452834713
    visualize: false
    map_voxel: 0.07018700647584232
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.0012618211837701165
    ieskf_sigma_accel: 0.006431873710461322
    ieskf_sigma_bg: 4.927943833148059e-05
    ieskf_sigma_ba: 0.002102034269871895
    ieskf_init_p_cov: 0.0947493245820518
    ieskf_init_bg_cov: 0.00026984365762961
    ieskf_init_ba_cov: 0.002444436163607055
    ieskf_init_g_cov: 0.0007786168294701699
    ieskf_max_iters: 3
    ieskf_meas_noise_pos: 0.0010748914956883687
    ieskf_meas_noise_rot: 0.010645766671035527
    imu_base_weight: 0.5207740910388896
    nonrep_base_weight: 0.4792259089611104
    gicp_min_conf: 0.3257272112414439
    gicp_chi2_threshold: 35.35975917962022
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.0381166811182574
    gicp_voxel_size: 0.10982981092427545
    gicp_max_iterations: 57
    gicp_submap_radius: 49.275760854229844
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
