lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.16855891475884832
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.008228989640942874
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 2.814665675232732
    motion_trans_pos_noise_scale: 2.3146146287068143
    visualize: false
    map_voxel: 0.09773770030754393
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.009222823702820631
    ieskf_sigma_accel: 0.09714664375797878
    ieskf_sigma_bg: 3.5883425149316924e-05
    ieskf_sigma_ba: 0.0009135480052464238
    ieskf_init_p_cov: 0.0014057027126860124
    ieskf_init_bg_cov: 0.032043981841057105
    ieskf_init_ba_cov: 0.0009863414033160782
    ieskf_init_g_cov: 0.0003734558493079895
    ieskf_max_iters: 6
    ieskf_meas_noise_pos: 0.00670188432353358
    ieskf_meas_noise_rot: 0.004667399495227591
    imu_base_weight: 0.32509138668837045
    nonrep_base_weight: 0.6749086133116295
    gicp_min_conf: 0.3745660889189928
    gicp_chi2_threshold: 56.22711176858572
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.6541803673767348
    gicp_voxel_size: 0.27632757931457375
    gicp_max_iterations: 84
    gicp_submap_radius: 16.83957697443907
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
