lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.02384264912981741
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.006836314065022723
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 1.0625691747807164
    motion_trans_pos_noise_scale: 2.602661782630072
    visualize: false
    map_voxel: 0.17620778267449794
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.004048966222584676
    ieskf_sigma_accel: 0.0023612399244412607
    ieskf_sigma_bg: 0.0006097025297491432
    ieskf_sigma_ba: 0.0011986281799901185
    ieskf_init_p_cov: 0.018707420137660268
    ieskf_init_bg_cov: 2.7555462077796642e-05
    ieskf_init_ba_cov: 8.160948743089913e-05
    ieskf_init_g_cov: 0.0051101206564971614
    ieskf_max_iters: 6
    ieskf_meas_noise_pos: 0.15109731920685004
    ieskf_meas_noise_rot: 0.11532752183396916
    imu_base_weight: 0.8343145311689459
    nonrep_base_weight: 0.16568546883105406
    gicp_min_conf: 0.28345577978451475
    gicp_chi2_threshold: 165.4228055252737
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.0393941530015727
    gicp_voxel_size: 0.10878904785643856
    gicp_max_iterations: 96
    gicp_submap_radius: 19.544131940933987
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
