lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.04539957141179767
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.024092145436664776
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 6.806555113685048
    motion_trans_pos_noise_scale: 0.9543955021244581
    visualize: false
    map_voxel: 0.2408090027508654
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.0018495216589727262
    ieskf_sigma_accel: 0.011790965486776316
    ieskf_sigma_bg: 1.5155823539597614e-05
    ieskf_sigma_ba: 0.00468387170811873
    ieskf_init_p_cov: 0.001455796149025199
    ieskf_init_bg_cov: 0.002309786149269356
    ieskf_init_ba_cov: 0.0051316549551483235
    ieskf_init_g_cov: 0.0001165068111898614
    ieskf_max_iters: 2
    ieskf_meas_noise_pos: 0.007341347358329406
    ieskf_meas_noise_rot: 0.002686486652554112
    imu_base_weight: 0.6190752475342215
    nonrep_base_weight: 0.3809247524657785
    gicp_min_conf: 0.46611212822535325
    gicp_chi2_threshold: 107.29768107686338
    use_pctools_gicp: true
    gicp_max_corr_distance: 4.715284949315305
    gicp_voxel_size: 0.06862635752322088
    gicp_max_iterations: 47
    gicp_submap_radius: 10.106308455826507
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
