lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.2639224534128997
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.0021317896707924036
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 1.7617838559512928
    motion_trans_pos_noise_scale: 0.3896248057757756
    visualize: false
    map_voxel: 0.19430151817746222
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.002218829091837419
    ieskf_sigma_accel: 0.04299053890306858
    ieskf_sigma_bg: 2.926568559599776e-05
    ieskf_sigma_ba: 0.000541842755138322
    ieskf_init_p_cov: 0.004829717206476616
    ieskf_init_bg_cov: 0.016455771261429435
    ieskf_init_ba_cov: 0.09833994401725078
    ieskf_init_g_cov: 0.00021937914085845466
    ieskf_max_iters: 6
    ieskf_meas_noise_pos: 0.019724639055274905
    ieskf_meas_noise_rot: 0.0121921454132297
    imu_base_weight: 0.6640379937957019
    nonrep_base_weight: 0.33596200620429806
    gicp_min_conf: 0.22525488997483342
    gicp_chi2_threshold: 87.21169501983204
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.7684290128930011
    gicp_voxel_size: 0.45683047096732343
    gicp_max_iterations: 24
    gicp_submap_radius: 14.699585742482412
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
