lio_node_v2:
  ros__parameters:
    lidar_topic: /avia/livox/points
    queue_size: 5
    use_imu: true
    imu_topic: /avia/livox/imu
    imu_gravity_mag: 9.81
    imu_gravity_init_n: 200
    imu_gravity_z_down: false
    imu_use_accel: true
    imu_timeout_sec: 0.5
    imu_accel_scale: 9.81
    imu_gyro_bias:
    - 0.0
    - 0.0
    - 0.0
    imu_accel_bias:
    - 0.0
    - 0.0
    - 0.0
    step_decimation: 1
    max_scans: -1
    accumulate_between_decimation: false
    accumulate_voxel: 0.1
    accumulate_max_points: 1500000
    force_z_zero: true
    soft_z_sigma: 0.07341896142396995
    zupt_omega_thresh: 0.05
    zupt_accel_thresh: 0.3
    zupt_sigma_v: 0.015310816824702325
    motion_omega_stationary: 0.05
    motion_omega_rotating: 0.3
    motion_accel_stationary: 0.3
    motion_accel_translating: 0.8
    motion_skip_stationary: true
    motion_rot_noise_scale: 4.689152288664869
    motion_trans_pos_noise_scale: 2.1998323661300883
    visualize: false
    map_voxel: 0.13965622722525173
    level_init: true
    imu_auto_scale: true
    undistort_translation: true
    ieskf_sigma_gyro: 0.003347092899342459
    ieskf_sigma_accel: 0.03764827481996307
    ieskf_sigma_bg: 3.4401059184604955e-05
    ieskf_sigma_ba: 0.0013883191208705398
    ieskf_init_p_cov: 0.0010032459667122875
    ieskf_init_bg_cov: 0.007410785953495469
    ieskf_init_ba_cov: 0.0005243666133194892
    ieskf_init_g_cov: 0.0015777201030456268
    ieskf_max_iters: 5
    ieskf_meas_noise_pos: 0.0047850440705165115
    ieskf_meas_noise_rot: 0.001846753486227619
    imu_base_weight: 0.13900922860913312
    nonrep_base_weight: 0.8609907713908669
    gicp_min_conf: 0.3521464238611618
    gicp_chi2_threshold: 57.9143031991709
    use_pctools_gicp: true
    gicp_max_corr_distance: 1.013576379353843
    gicp_voxel_size: 0.27526897603686795
    gicp_max_iterations: 100
    gicp_submap_radius: 27.648783483705536
    voxel_map_prune_radius: 80.0
    voxel_map_max_voxels: 400000
    publish_odom: true
    odom_topic: /lio_v2/odom
    publish_map: false
    publish_tf: false
    map_frame: map
    base_frame: base_link
